#gives you the complentary seq of a dna seq but in reverse

def reverse_complement(seq):
	rna_seq=[]
	for Nuc in seq:
		if Nuc=='A':
			rna_seq.append('T')
		if Nuc=='T':
			rna_seq.append('A')
		if Nuc=='C':
			rna_seq.append('G')
		if Nuc=='G':
			rna_seq.append('C')
	
	#reversing the string	
	var=rna_seq[::-1]
	return var
validation=reverse_complement('TCTGAGCCCGGTTTGAGGAGTTTGACTCCACCGGATCAGGCCATTACATCATATCCCATGGGTGTTCATCAGTACGGGCACCTCGCCCAAGACCCAAGATACTCCGTCTGTAGGGAAACAACCGGGTTCGCGAACACTGGAAATGCTGAGTGTGTCTGACTTCCTATGAGCAAGCCCCTGCGCAGGCTGGATTTAGAGCCCTCGTTTGAATGTCCAGACACAGGGGAACTGTTCCCGCCGACGTACCTACGATTAGCGTACATCGATTTCAATATGGGCATCGGTTATGCGGTCATCCGGGGGAACACGGGCCGGATAGTGGGCTACGGGCAATCCCGCCTGAATTTCTTGTCAGCATTCGGACGACGCTGTGGAAGGCCTCCGGGGGCCAAGTAGTGGGCCTCCGTATGGTTCCTCTGCGGGTACCATGATACATCGTAAACGCTTAAGGGGGAGGCGTGTATCACGTTGGCATCCATTCATCCGTGCAAATGCGTATACGTTTAGCTGGACTCAGCCGGTTAAGGTTCTCGGCTGTGGACGAGAGATGCAGTCAAAAATTTCCAAATAAGACTCGTTCACTTGTTTGCGTCATGTCGATGCTCAAATTCGTTCACATGTGCGGGACCTATCTGGTGCAGTTCCAACGACAGTTTAGCGTAGCTATGCCAATGAACGGACGAGCCCCGAGATGAGAATAACCTGGGAAGAGCCACGCAACGCAACTCGCGCCTAGAAGACTGGCATAGTGTCTGACCCGTACGGTGATTCGAGCGGTCGTCTGCGTCAATTGCTGGGGTAGTGTCAGAGCCTTTAGCGCCGTTTTGGTGAGAGCCTCCAGACGTATGTTAATTTAGTGCTATTCGAACAACCCTTTAGGTGCTTGTGC')
print(''.join(str(i) for i in validation))
